apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-backend
  namespace: app-travelexample
  labels:
    app: travel-backend
    component: backend
spec:
  replicas: 1  # Single replica due to in-memory state management
  selector:
    matchLabels:
      app: travel-backend
  template:
    metadata:
      labels:
        app: travel-backend
        component: backend
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: travel-backend
        image: ghcr.io/smpnet74/coagents-travel-backend:latest
        imagePullPolicy: Always  # Always pull from registry
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: travel-secrets
              key: OPENAI_API_KEY
        - name: GOOGLE_MAPS_API_KEY
          valueFrom:
            secretKeyRef:
              name: travel-secrets
              key: GOOGLE_MAPS_API_KEY
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /docs
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /docs
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /docs
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6