apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: travel-gateway-access
  namespace: default
spec:
  from:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    namespace: app-travelexample
  to:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: default-gateway